# This file was generated by GoReleaser. DO NOT EDIT.
cask "orbit-sentinel-mcp" do
  version "0.6.6"

  on_macos do
    on_arm do
      sha256 "31117a2154d240b5cf7a4e40083d9c7634f1797ca48489c47e6d8e78067a226d"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4da8d5e7ec489aecda608043e2c4f0252bb5cf1ad333656c8d544722d7f4d846"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e5d7b39af1dfa7c460ecc90abef1b7012f9f320cb9713594e1575039ec517ef6"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b49bab1384c9b7bbad78036e95d88c58bfd722bcbcc6a4d6a52cd4173923177"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_linux_amd64.tar.gz"
    end
  end

  name "orbit-sentinel-mcp"
  desc "MCP server for Orbit Sentinel — space regulatory filings from FCC, ITU, UNOOSA, FAA-AST"
  homepage "https://github.com/viventine-space/orbit-sentinel-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orbit-sentinel-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orbit-sentinel-mcp"]
    end
  end

  # No zap stanza required
end
