# This file was generated by GoReleaser. DO NOT EDIT.
cask "orbit-sentinel-mcp" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "9870834dcc6d30270dbe2691cbe6b572ca7c0c276adffb1807651d9ddf031459"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "53ad3f05b3b61cccd4b01a8fc5ea8e3416adfa0dd0bf0643fc41e355847ba37c"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ef5820806c7be03c19f79007356aa3cb0a724fd2957e0440cbd5be62849b528"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9d4c793acd4eb0ff45fba41c27eaf73be6d87615324902fa47c1a95b8167e9af"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_linux_arm64.tar.gz"
    end
  end

  name "orbit-sentinel-mcp"
  desc "MCP server for Orbit Sentinel — space regulatory filings from FCC, ITU, UNOOSA, FAA-AST"
  homepage "https://github.com/viventine-space/orbit-sentinel-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orbit-sentinel-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orbit-sentinel-mcp"]
    end
  end

  # No zap stanza required

end
