# This file was generated by GoReleaser. DO NOT EDIT.
cask "orbit-sentinel-mcp" do
  version "0.6.5"

  on_macos do
    on_arm do
      sha256 "203ae50f2ffa454d791de013290d7fc910256e5f22dee8651f3c32b25810c862"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b2940e52c642855d87af1b1dbddb8cca96ed4ceac45cf6c0b3e1dbe5c3b4b59"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ccc6c8a4c3470c8e6ebf6157ba582c22d4e5ca73fc17215f338bb4dfafc27d9a"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "24a7c9a0633a682b16bc0664321ea9aebc3caa0f99cf795bb9351d81cfd3bdf7"
      url "https://github.com/Viventine-Space/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_linux_amd64.tar.gz"
    end
  end

  name "orbit-sentinel-mcp"
  desc "MCP server for Orbit Sentinel — space regulatory filings from FCC, ITU, UNOOSA, FAA-AST"
  homepage "https://github.com/viventine-space/orbit-sentinel-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orbit-sentinel-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orbit-sentinel-mcp"]
    end
  end

  # No zap stanza required
end
